# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emailuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='emailuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 9, 19, 23, 23, 909948, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
