# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-15 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160309_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2Token',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_oauth2token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(default='', max_length=254)),
                ('refresh_token', models.CharField(default='', max_length=254)),
                ('token_expiry', models.CharField(default='', max_length=254)),
                ('code', models.CharField(blank=True, max_length=254)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UserOauth2Token',
                'verbose_name_plural': 'UserOauth2Tokens',
                'ordering': ('user', 'updated_at'),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='emailuser',
            name='google_oauth2_client_id',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='google_oauth2_secrete',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='oauth2token',
            unique_together=set([('user',)]),
        ),
    ]
