# Generated by Django 2.2.6 on 2019-10-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191014_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailuser',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ['-id'], 'permissions': (('view_emailuser', 'Can view email users'),)},
        ),
    ]
